name: macos-next-full

on:
  workflow_dispatch:

jobs:
  full:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash macos-next/tools/build.sh
      - name: Full install (non-dry-run, no VS Code)
        run: |
          macos-next/dist/dtu-python-installer-macos.sh --yes
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-next-full-logs
          path: |
            /tmp/dtu_macos_next_*.log
            /tmp/macos_next_precheck_*.env
          if-no-files-found: ignore

